name: CRON
on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  update-stylelint4b:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - name: Install Packages
      run: npm install
    - name: Update
      uses: ./.github/actions/update-stylelint4b
      id: updateStylelint4b
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Build
      run: cd ./packages/stylelint4b && npm run build
      if: success() && steps.updateStylelint4b.outputs.updated == 1
    - name: check can npm-publish && release
      run: |
        cd ./packages/stylelint4b
        npx can-npm-publish && npm publish || true
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      if: success() && steps.updateStylelint4b.outputs.updated == 1
