name: CRON
on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * *"

jobs:
  update-stylelint4b:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
    - name: setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 14
        registry-url: 'https://registry.npmjs.org'
    - name: Install Packages
      run: npm install
    - name: Update
      uses: ./.github/actions/update-stylelint4b
      id: updateStylelint4b
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Build
      run: cd ./packages/stylelint4b && npm run build
      if: success() && steps.updateStylelint4b.outputs.updated == 1
    - name: Test
      run: cd ./packages/stylelint4b && npm run test
      if: success() && steps.updateStylelint4b.outputs.updated == 1
    - name: check can npm-publish
      run: |
        cd ./packages/stylelint4b
        npx can-npm-publish
      if: success() && steps.updateStylelint4b.outputs.updated == 1
    - name: Release
      run: |
        cd ./packages/stylelint4b
        npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
        npm publish
      env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      if: success() && steps.updateStylelint4b.outputs.updated == 1
