name: GHPages

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Install Packages
      run: npm install
    - name: Build
      run: |+
        npm run build
        npm run docs:build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/.vuepress/dist
        force_orphan: true
