name: GHPages

on:
  push:
    branches: [master]
  workflow_dispatch: null

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 18
    - name: Install Packages
      run: npm install --legacy-peer-deps
    - name: Build docs
      run: |+
        export NODE_OPTIONS=--openssl-legacy-provider
        npm run build
        npm run docs:build
        npm run docs:sample-copy
    - name: Setup Pages
      uses: actions/configure-pages@v5
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: ./docs/.vuepress/dist
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
