name: publish
on:
  push:
    tags:
      - "*"
jobs:
  release-stylelint4b:
    name: check version, and release for stylelint4b
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: setup Node
      uses: actions/setup-node@v1
      with:
        registry-url: 'https://registry.npmjs.org'
    - name: Install Packages
      run: npm install
    - name: Build
      run: cd ./packages/stylelint4b && npm run build
    - name: check can npm-publish && release
      run: |
        cd ./packages/vue-stylelint-editor
        npx can-npm-publish && npm publish || true
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  release-vue-stylelint-editor:
    name: check version, and release for vue-stylelint-editor
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: setup Node
      uses: actions/setup-node@v1
      with:
        registry-url: 'https://registry.npmjs.org'
    - name: Install Packages
      run: npm install
    - name: Build
      run: cd ./packages/vue-stylelint-editor && npm run build
    - name: check can npm-publish && release
      run: |
        cd ./packages/vue-stylelint-editor
        npx can-npm-publish && npm publish || true
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
